---
# ====== Application: Sample Application Search ==============
id: 7190
identification: 
  name: Sample Application Search
  alias: SAMPLE-APPLICATION-SEARCH222776222
  version: 22.2.0

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1 / 22.2
  copyright-banner: |
    Name: #APP_NAME#
    Copyright (c) 2012, #YEAR# Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0
    as shown at https://oss.oracle.com/licenses/upl/

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 3292185646772710792

authorization: 
  authorization-scheme: MODEL.LOV.MUST_NOT_BE_PUBLIC_USER
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: DEMO

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Sample Application Search

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Black Text and White Background

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu # 3292349289173710902
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 3292186413923710794

navigation-bar: 
  implementation: List
  list: Navigation Bar # 3292386691476710927
  list-template: Navigation Bar # 3292348933472710901
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: true

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 852320622354339933
  identification: 
    name: APP_NAME

  value: 
    static-value: Sample Application Search

