prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/tmdb_api_key.sql
@@workspace/remote_servers/api_themoviedb_org_3.sql
@@application/shared_components/data_profiles/movie_details.sql
@@application/shared_components/data_profiles/company_details.sql
@@application/shared_components/data_profiles/moviedb.sql
@@application/shared_components/data_profiles/search_company.sql
@@application/shared_components/web_sources/movie_details.sql
@@application/shared_components/web_sources/company_details.sql
@@application/shared_components/web_sources/search_movie.sql
@@application/shared_components/web_sources/search_company.sql
@@application/shared_components/navigation/lists/administration.sql
@@application/shared_components/navigation/lists/oracle_text.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/home.sql
@@application/shared_components/navigation/lists/basics.sql
@@application/shared_components/navigation/lists/use_cases.sql
@@application/shared_components/navigation/lists/advanced.sql
@@application/shared_components/files/product_images_zip.sql
@@application/shared_components/files/image_not_found_png.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/oracle_text_is_available.sql
@@application/shared_components/security/authorizations/web_credentials_not_provided.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/load_products_images.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/product_colors.sql
@@application/pages/page_groups.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/drawer.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/image.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_drawer.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/item_container.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/search_results_container.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/navigation/search_config/product_search_configuration_oracle_text.sql
@@application/shared_components/navigation/search_config/product_search_configuration_oracle_text_function.sql
@@application/shared_components/navigation/search_config/cancelled_orders_search_configuration.sql
@@application/shared_components/navigation/search_config/product_search_configuration_with_image.sql
@@application/shared_components/navigation/search_config/product_search_configuration.sql
@@application/shared_components/navigation/search_config/store_search_configuration.sql
@@application/shared_components/navigation/search_config/movie_search_configuration.sql
@@application/shared_components/navigation/search_config/company_search_configuration.sql
@@application/shared_components/navigation/search_config/product_search_configuration_with_prefix.sql
@@application/shared_components/navigation/search_config/store_search_configuration_with_prefix.sql
@@application/shared_components/navigation/search_config/customer_search_configuration.sql
@@application/shared_components/navigation/search_config/product_search_configuration_custom_display.sql
@@application/shared_components/navigation/search_config/store_search_configuration_with_location.sql
@@application/shared_components/navigation/search_config/complete_orders_search_configuration.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00100.sql
@@application/pages/page_00101.sql
@@application/pages/page_00102.sql
@@application/pages/page_00103.sql
@@application/pages/page_00104.sql
@@application/pages/page_00105.sql
@@application/pages/page_00106.sql
@@application/pages/page_00200.sql
@@application/pages/page_00201.sql
@@application/pages/page_00202.sql
@@application/pages/page_00203.sql
@@application/pages/page_00204.sql
@@application/pages/page_00205.sql
@@application/pages/page_00206.sql
@@application/pages/page_00207.sql
@@application/pages/page_00300.sql
@@application/pages/page_00301.sql
@@application/pages/page_00302.sql
@@application/pages/page_00303.sql
@@application/pages/page_00304.sql
@@application/pages/page_00400.sql
@@application/pages/page_00401.sql
@@application/pages/page_00402.sql
@@application/pages/page_00500.sql
@@application/pages/page_00501.sql
@@application/pages/page_00502.sql
@@application/pages/page_00503.sql
@@application/pages/page_00600.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_install.sql
@@application/deployment/install/install_data.sql
@@application/deployment/install/install_oracle_text_helper_package_compiles_without_oracle_text.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
