  CREATE TABLE "EBA_DEMO_SEARCH_ORDERS" 
   (	"ORDER_ID" NUMBER DEFAULT ON NULL to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') NOT NULL ENABLE,
	"ORDER_DATETIME" TIMESTAMP(6) NOT NULL ENABLE,
	"CUSTOMER_ID" NUMBER NOT NULL ENABLE,
	"ORDER_STATUS" VARCHAR2(10) NOT NULL ENABLE,
	"STORE_ID" NUMBER NOT NULL ENABLE,
	"TEST" NUMBER,
	CONSTRAINT "EBA_DEMO_SEARCH_ORDER_STATUS_C" CHECK (order_status in ('CANCELLED','COMPLETE','OPEN','PAID','REFUNDED','SHIPPED')) ENABLE,
	CONSTRAINT "EBA_DEMO_SEARCH_ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX ENABLE,
	CONSTRAINT "EBA_DEMO_SEARCH_ORD_CUST_ID_FK" FOREIGN KEY ("CUSTOMER_ID")
	 REFERENCES "EBA_DEMO_SEARCH_CUSTOMERS" ("CUSTOMER_ID") ON DELETE CASCADE ENABLE,
	CONSTRAINT "EBA_DEMO_SEARCH_ORD_STR_ID_FK" FOREIGN KEY ("STORE_ID")
	 REFERENCES "EBA_DEMO_SEARCH_STORES" ("STORE_ID") ON DELETE CASCADE ENABLE
   )