  CREATE TABLE "EBA_DEMO_SEARCH_PRODUCTS" 
   (	"PRODUCT_ID" NUMBER DEFAULT ON NULL to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') NOT NULL ENABLE,
	"PRODUCT_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"UNIT_PRICE" NUMBER(10,2),
	"PRODUCT_DETAILS" BLOB,
	"PRODUCT_IMAGE" BLOB,
	"IMAGE_MIME_TYPE" VARCHAR2(512),
	"IMAGE_FILENAME" VARCHAR2(512),
	"IMAGE_CHARSET" VARCHAR2(512),
	"IMAGE_LAST_UPDATED" DATE,
	"TEXT_INDEX_COLUMN" VARCHAR2(255),
	CONSTRAINT "EBA_DEMO_SEARCH_PRODUCT_JSON_C" CHECK (product_details is json) ENABLE,
	CONSTRAINT "EBA_DEMO_SEARCH_PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX ENABLE
   )