  CREATE TABLE "EBA_DEMO_SEARCH_STORES" 
   (	"STORE_ID" NUMBER DEFAULT ON NULL to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX') NOT NULL ENABLE,
	"STORE_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"WEB_ADDRESS" VARCHAR2(100),
	"PHYSICAL_ADDRESS" VARCHAR2(512),
	"LATITUDE" NUMBER,
	"LONGITUDE" NUMBER,
	"LOGO" BLOB,
	"LOGO_MIME_TYPE" VARCHAR2(512),
	"LOGO_FILENAME" VARCHAR2(512),
	"LOGO_CHARSET" VARCHAR2(512),
	"LOGO_LAST_UPDATED" DATE,
	CONSTRAINT "EBA_DEMO_SEARCH_REQUIRED_ADR_C" CHECK (coalesce ( web_address, physical_address ) is not null) ENABLE,
	CONSTRAINT "EBA_DEMO_SEARCH_STORES_PK" PRIMARY KEY ("STORE_ID")
  USING INDEX ENABLE,
	CONSTRAINT "EBA_DEMO_SEARCH_STORE_NAME_U" UNIQUE ("STORE_NAME")
  USING INDEX ENABLE
   )